# Generated by Django 5.1.3 on 2024-12-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("vegetarian", "Vegetarian"),
                            ("low_carb", "Low Carb"),
                            ("high_protein", "High Protein"),
                            ("vegan", "Vegan"),
                        ],
                        max_length=50,
                    ),
                ),
                ("calories", models.IntegerField()),
                (
                    "ingredients",
                    models.ManyToManyField(to="meal_recommendation.ingredient"),
                ),
            ],
        ),
    ]
