# Generated by Django 5.1.3 on 2024-12-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal_recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="carbs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cook_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="fiber",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="prep_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="preparation_steps",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="protein",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="sugar",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="total_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("Healthy", "Healthy"),
                    ("Vegetarian", "Vegetarian"),
                    ("Low Carb", "Low Carb"),
                    ("High Protein", "High Protein"),
                    ("Vegan", "Vegan"),
                    ("Snacks", "Snacks"),
                ],
                max_length=50,
            ),
        ),
    ]
